# Generated by Django 2.2.7 on 2019-11-07 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordertaker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
