# Generated by Django 2.2.7 on 2019-11-07 21:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ordertaker', '0002_auto_20191107_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='addons',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sugar_level',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
