# Generated by Django 2.2.7 on 2019-11-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordertaker', '0005_auto_20191107_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='menu',
            new_name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(default='', max_length=5),
        ),
    ]
